config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :people
  resources :categories
  resources :users
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "events#timeline"
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  # GET /places or /places.json
  def index
    @places = Place.all
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to place_url(@place), notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_url(@place), notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy!

    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :lat, :lon)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place) do |form| %>
  <% if place.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :lat, style: "display: block" %>
    <%= form.text_field :lat %>
  </div>

  <div>
    <%= form.label :lon, style: "display: block" %>
    <%= form.text_field :lon %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/places/_place.html.erb
<div id="<%= dom_id place %>">
  <p>
    <strong>Name:</strong>
    <%= place.name %>
  </p>

  <p>
    <strong>Lat:</strong>
    <%= place.lat %>
  </p>

  <p>
    <strong>Lon:</strong>
    <%= place.lon %>
  </p>

</div>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render "form", place: @place %>

<br>

<div>
  <%= link_to "Show this place", @place %> |
  <%= link_to "Back to places", places_path %>
</div>

app/views/places/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Places</h1>

<div id="places">
  <% @places.each do |place| %>
    <%= render place %>
    <p>
      <%= link_to "Show this place", place %>
    </p>
  <% end %>
</div>

<%= link_to "New place", new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render "form", place: @place %>

<br>

<div>
  <%= link_to "Back to places", places_path %>
</div>

app/views/places/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @place %>

<div>
  <%= link_to "Edit this place", edit_place_path(@place) %> |
  <%= link_to "Back to places", places_path %>

  <%= button_to "Destroy this place", @place, method: :delete %>
</div>